#上传文件的存储路径以及文件大小限制
[Repo]
UploadPath = "/opt/upload/"
MaxSize = 8388608
[MySql]
Name = "yourdb"
Host = "127.0.0.1:3306"
Username = "root"
Password = "root"
[Lotus]
Host = "127.0.0.1:1234"
Lotus = "172.0.0.1:1234"
Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.yhAuAdMFDPXh3iqcr5RCkjaXCNi8-zye4i1Ci9Z72yM"
[Redis]
Host = "127.0.0.1:6379"
Password = ""
[Project]
Host = "9000"